CREATE TABLE api_clients (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id              VARCHAR(64)  NOT NULL UNIQUE,
    client_name            VARCHAR(255) NOT NULL,
    api_key_hash           VARCHAR(64)  NOT NULL UNIQUE,
    default_limit          INTEGER      NOT NULL,
    default_window_seconds INTEGER      NOT NULL,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMP    NOT NULL
);
CREATE INDEX idx_api_clients_key_hash ON api_clients (api_key_hash);
